### PR TITLE
Prefer MathJax if it is available

### PR DESCRIPTION
**Pull request by blink1073**

### CODE REVIEW

**Comment by blink1073** [comment]
cc @jasongrout

**Comment by blink1073** [comment]
cc @minrk

**Comment by blink1073** [comment]
cc @jdfreder

**Comment by blink1073** [comment]
Ack!  There was a typo!  Where is a TypeScript compiler when you need one... new PR coming.

**Comment by rgbkrk** [comment]
@blink1073 totally cool if you introduce TypeScript over here

**Comment by rgbkrk** [comment]
Also, very cool. :)

**Comment by rgbkrk** [comment]
Also seems reasonable to write a test since this is conditionally based on a global mathjax being defined.

**Pull request merged**
